import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'OBSIDIAN OVERSIZED HOODIE',
    nameAr: 'هودي أوبسيديان بقصة واسعة',
    price: 340,
    costPrice: 180,
    originalPrice: 420,
    discountPercentage: 20,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800&h=1000',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&q=80&w=800&h=1000'
    ],
    category: 'OUTERWEAR',
    gender: 'Unisex',
    collectionName: 'Obsidian Drop',
    colorName: 'Onyx Black',
    colorHex: '#121212',
    material: 'Heavyweight Fleece',
    fit: 'Over-sized',
    brand: 'AVENTO7 Atelier',
    isNew: true,
    rating: 4.8,
    reviews: 124,
    description: 'Crafted from heavyweight premium cotton. Features an oversized fit, dropped shoulders, and a structured hood. A versatile piece for your core rotation.',
    descriptionAr: 'مصنوع من قطن ثقيل فاخر. يتميز بقصة واسعة جداً، وأكتاف منسدلة، وغطاء رأس متماسك. قطعة أساسية لا غنى عنها.',
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: '2',
    name: 'TAILORED CARGO TROUSERS',
    nameAr: 'بنطال كارغو مفصل',
    price: 420,
    costPrice: 210,
    image: 'https://images.unsplash.com/photo-1622312686161-5f2122bc6625?auto=format&fit=crop&q=80&w=800&h=1000',
    images: [
      'https://images.unsplash.com/photo-1622312686161-5f2122bc6625?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&q=80&w=800&h=1000'
    ],
    category: 'BOTTOMS',
    gender: 'Men',
    collectionName: 'Core Essentials',
    colorName: 'Slate Grey',
    colorHex: '#4A5568',
    material: 'Nylon Blend',
    fit: 'Tailored',
    brand: 'AVENTO7 Mainline',
    rating: 4.9,
    reviews: 89,
    description: 'Utilitarian design refined with tailored constraints. Italian nylon blend fabric, gusseted pockets, and articulated knee darts.',
    descriptionAr: 'تصميم عملي بلمسات راقية ومفصلة. مزيج من النايلون الإيطالي، وجيوب مزودة بوصلات، وخياطة عند منطقة الركبة لحرية الحركة.',
    sizes: ['28', '30', '32', '34', '36']
  },
  {
    id: '3',
    name: 'HEAVYWEIGHT BOX TEE',
    nameAr: 'تيشيرت بقصة صندوقية',
    price: 185,
    costPrice: 85,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800&h=1000',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=800&h=1000'
    ],
    category: 'TOPS',
    gender: 'Unisex',
    collectionName: 'Core Essentials',
    colorName: 'Pure Ivory',
    colorHex: '#F8F9FA',
    material: '100% Egyptian Cotton',
    fit: 'Boxy Fit',
    brand: 'AVENTO7 Mainline',
    rating: 4.5,
    reviews: 240,
    description: 'The foundation of the collection. Extreme heavyweight 320gsm cotton jersey, cropped perfectly at the waist with slightly extended sleeves.',
    descriptionAr: 'حجر الأساس في هذه التشكيلة. جيرسي قطني بوزن 320 جرام، مقصوص بشكل مثالي عند الخصر مع أكمام أطول قليلاً.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: '4',
    name: 'ASYMMETRIC ZIP VEST',
    nameAr: 'سترة بسحاب غير متماثل',
    price: 550,
    costPrice: 280,
    originalPrice: 700,
    discountPercentage: 25,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800&h=1000',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=800&h=1000',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800&h=1000'
    ],
    category: 'OUTERWEAR',
    gender: 'Women',
    collectionName: 'Velvet Night',
    colorName: 'Burgundy Rose',
    colorHex: '#30001A',
    material: 'Velvet Blend',
    fit: 'Regular Fit',
    brand: 'AVENTO7 Atelier',
    isNew: true,
    rating: 5.0,
    reviews: 42,
    description: 'Tactical aesthetics featuring dual asymmetric zippers, magnetic closures, and hidden interior pockets. Water-repellent finish.',
    descriptionAr: 'جماليات تكتيكية بامتياز تتميز بسحابات مزدوجة غير متماثلة، وأزرار إغلاق مغناطيسية، وجيوب داخلية مخفية. طلاء مقاوم للماء.',
    sizes: ['XS', 'S', 'M']
  },
  {
    id: '5',
    name: 'STRUCTURAL BLAZER',
    nameAr: 'بليزر بتصميم هيكلي',
    price: 890,
    costPrice: 420,
    image: 'https://images.unsplash.com/photo-1592305886638-0aa32bc13d5d?auto=format&fit=crop&q=80&w=800&h=1000',
    category: 'OUTERWEAR',
    gender: 'Women',
    collectionName: 'Winter Luxe',
    colorName: 'Midnight Navy',
    colorHex: '#0B132B',
    material: 'Wool Gabardine',
    fit: 'Tailored',
    brand: 'AVENTO7 Atelier',
    rating: 4.7,
    reviews: 73,
    description: 'Aggressive shoulder structure offset by a sculpted, cinched waist. Premium wool gabardine construction with silk lining.',
    descriptionAr: 'بنية أكتاف بارزة يقابلها خصر مشدود ومنحوت. مصنوع من جبردين الصوف الفاخر مع بطانة من الحرير النقي.',
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: '6',
    name: 'TECHNICAL PLEATED PANT',
    nameAr: 'بنطال بطيات تقنية',
    price: 360,
    costPrice: 170,
    originalPrice: 450,
    discountPercentage: 20,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&q=80&w=800&h=1000',
    category: 'BOTTOMS',
    gender: 'Women',
    collectionName: 'Summer Atelier',
    colorName: 'Champagne Gold',
    colorHex: '#D4AF37',
    material: 'Silk Blend',
    fit: 'Slim Fit',
    brand: 'AVENTO7 Sport',
    isNew: true,
    rating: 4.6,
    reviews: 58,
    description: 'Fluid movement meets architectural lines. Permanent micro-pleats on a lightweight, wrinkle-resistant technical fabric.',
    descriptionAr: 'مرونة الحركة تلتقي بالخطوط المعمارية. طيات صغيرة دائمة على قماش تقني خفيف الوزن ومقاوم للتجعد.',
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: '7',
    name: 'MOCK NECK SCUBA TOP',
    nameAr: 'توب ياقة عالية قماش سكوبا',
    price: 140,
    costPrice: 65,
    image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?auto=format&fit=crop&q=80&w=800&h=1000',
    category: 'TOPS',
    gender: 'Women',
    collectionName: 'Core Essentials',
    colorName: 'Onyx Black',
    colorHex: '#121212',
    material: '100% Egyptian Cotton',
    fit: 'Slim Fit',
    brand: 'AVENTO7 Mainline',
    rating: 4.4,
    reviews: 112,
    description: 'Double-knit scuba fabric offering structure and stretch. Minimalist mock neck and hidden side zip entry.',
    descriptionAr: 'قماش سكوبا مزدوج الحياكة يوفر بنية متماسكة وتمدد. ياقة عالية بسيطة وسحاب جانبي مخفي.',
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: '8',
    name: 'OVERSIZED MOTO JACKET',
    nameAr: 'جاكيت دراجات بقصة واسعة',
    price: 1250,
    costPrice: 650,
    image: 'https://images.unsplash.com/photo-1520975954732-57dd22299614?auto=format&fit=crop&q=80&w=800&h=1000',
    category: 'OUTERWEAR',
    gender: 'Men',
    collectionName: 'Obsidian Drop',
    colorName: 'Onyx Black',
    colorHex: '#121212',
    material: 'Vegan Leather',
    fit: 'Over-sized',
    brand: 'AVENTO7 Atelier',
    isNew: true,
    isPreOrder: true,
    rating: 4.9,
    reviews: 21,
    description: 'Heavyweight calf leather treated for a matte finish. Exaggerated proportions and heavy-duty silver hardware.',
    descriptionAr: 'جلد عجل ثقيل معالج لمنحه لمسة غير لامعة. أبعاد ضخمة وقطع معدنية فضية شديدة التحمل.',
    sizes: ['S', 'M', 'L', 'XL']
  }
];
